// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iyajhziagcinxqncxygi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5YWpoemlhZ2NpbnhxbmN4eWdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNDY1NDYsImV4cCI6MjA2NzYyMjU0Nn0.gVpoM_gcAXxjOsV1kCYPkaNPQlBJzhdu0n8sRmbHciI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});